language: python

python:
  - "3.3"

before_install:
  - pip install numpy
  - pip install python-dateutil
  - pip install pytz
  - pip install scipy
  - pip install h5py
  - pip install shapely
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran

install: 
  - pip install --use-mirrors pyparsing
  - pip install --use-mirrors matplotlib

script: nosetests

notifications: 
  email: false
  
