# Courtesy https://gist.github.com/dan-blanchard/7045057

language: python
python:
  - 2.7
  - 3.3
  - 3.4
notifications:
  email: false
 
before_install:
  # Anaconda installation
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # https://github.com/hackcasual/firstpythonfortravis/blob/master/.travis.yml
  #- sudo apt-get update
  #- sudo apt-get install python-opencv
  #- sudo dpkg -L python-opencv  
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - sudo /bin/cp $TRAVIS_BUILD_DIR/movement_validation/user_config_example.txt $TRAVIS_BUILD_DIR/movement_validation/user_config.py

  # Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels h5py shapely
  #opencv 3
  - conda install -y -c https://conda.binstar.org/hadim opencv
  # Coverage packages are on my binstar channel
  # The next line currently fails with the error "Error: Unsatisfiable package specifications.  
  #                                               Hint: the following packages conflict with each other:
  #                                               - nose-cov
  #                                               - python 3.4*   "
  #- conda install --yes -c dan_blanchard python-coveralls nose-cov
#  - python setup.py install
 
# Run test
script:
  - nosetests
#  - nosetests --with-cov --cov YOUR_PACKAGE_NAME_HERE --cov-config .coveragerc --logging-level=INFO

 
# Calculate coverage
#after_success:
#  - coveralls --config_file .coveragerc
