language: python

python:
  - "3.4"

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests

script:
  - nosetests

# TODO: add coveralls (following this example: https://github.com/tatsy/tython/blob/master/.travis.yml)
# then eventually, have a deployed website  like this: http://conda.pydata.org/miniconda.html#miniconda
# or maybe just get the package to show up in pip
